apiVersion: v1
kind: Service
metadata:
  namespace: beta-gormsqlite
  labels:
    app: beta-gormsqlite
  name: beta-gormsqlite
spec:
  ports:
  
    - protocol: TCP
      port: 9800
      targetPort: 9800
   
   
  selector:
    app: beta-gormsqlite
  type: ClusterIP
