apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: alpha
  name: alpha
  labels:
    app: alpha
spec:
  selector:
    matchLabels:
      app: alpha
  template:
    metadata:
      labels:
        app: alpha
        name: alpha
    spec:
      containers:
        - name: alpha
          image: azar-intelops/microservice-demo/alpha
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 9796
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        