apiVersion: v1
kind: Service
metadata:
  namespace: alpha
  labels:
    app: alpha
  name: alpha
spec:
  ports:
  
    - protocol: TCP
      port: 9796
      targetPort: 9796
   
   
  selector:
    app: alpha
  type: ClusterIP
