apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: alpha2
  name: alpha2
  labels:
    app: alpha2
spec:
  selector:
    matchLabels:
      app: alpha2
  template:
    metadata:
      labels:
        app: alpha2
        name: alpha2
    spec:
      containers:
        - name: alpha2
          image: azar-intelops/microservice-demo/alpha2
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 8020
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        