apiVersion: v1
kind: Service
metadata:
  namespace: alpha2
  labels:
    app: alpha2
  name: alpha2
spec:
  ports:
  
    - protocol: TCP
      port: 8020
      targetPort: 8020
   
   
  selector:
    app: alpha2
  type: ClusterIP
