apiVersion: v1
kind: Service
metadata:
  namespace: alpha-sqlite
  labels:
    app: alpha-sqlite
  name: alpha-sqlite
spec:
  ports:
  
    - protocol: TCP
      port: 9800
      targetPort: 9800
   
   
  selector:
    app: alpha-sqlite
  type: ClusterIP
