apiVersion: v1
kind: Service
metadata:
  namespace: alpha-mysql
  labels:
    app: alpha-mysql
  name: alpha-mysql
spec:
  ports:
  
    - protocol: TCP
      port: 9800
      targetPort: 9800
   
   
  selector:
    app: alpha-mysql
  type: ClusterIP
