apiVersion: v1
kind: Service
metadata:
  namespace: alpha4
  labels:
    app: alpha4
  name: alpha4
spec:
  ports:
  
    - protocol: TCP
      port: 9800
      targetPort: 9800
   
   
  selector:
    app: alpha4
  type: ClusterIP
