apiVersion: v1
kind: Service
metadata:
  namespace: gamma
  labels:
    app: gamma
  name: gamma
spec:
  ports:
  
    - protocol: TCP
      port: 9800
      targetPort: 9800
   
   
  selector:
    app: gamma
  type: ClusterIP
