apiVersion: v1
kind: Service
metadata:
  namespace: alpha3
  labels:
    app: alpha3
  name: alpha3
spec:
  ports:
  
    - protocol: TCP
      port: 9800
      targetPort: 9800
   
   
  selector:
    app: alpha3
  type: ClusterIP
