apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beta-mysql
  name: beta-mysql
  labels:
    app: beta-mysql
spec:
  selector:
    matchLabels:
      app: beta-mysql
  template:
    metadata:
      labels:
        app: beta-mysql
        name: beta-mysql
    spec:
      containers:
        - name: beta-mysql
          image: azar-intelops/microservice-demo/beta-mysql
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 9800
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        