apiVersion: v1
kind: Service
metadata:
  namespace: beta-mysql
  labels:
    app: beta-mysql
  name: beta-mysql
spec:
  ports:
  
    - protocol: TCP
      port: 9800
      targetPort: 9800
   
   
  selector:
    app: beta-mysql
  type: ClusterIP
