apiVersion: v1
kind: Service
metadata:
  namespace: one2oneclient
  labels:
    app: one2oneclient
  name: one2oneclient
spec:
  ports:
  
    - protocol: TCP
      port: 9800
      targetPort: 9800
   
   
  selector:
    app: one2oneclient
  type: ClusterIP
