apiVersion: v1
kind: Service
metadata:
  namespace: gamma-sqlite
  labels:
    app: gamma-sqlite
  name: gamma-sqlite
spec:
  ports:
  
    - protocol: TCP
      port: 6000
      targetPort: 6000
   
   
  selector:
    app: gamma-sqlite
  type: ClusterIP
