apiVersion: v1
kind: Service
metadata:
  namespace: one2one
  labels:
    app: one2one
  name: one2one
spec:
  ports:
  
    - protocol: TCP
      port: 9800
      targetPort: 9800
   
   
  selector:
    app: one2one
  type: ClusterIP
