apiVersion: v1
kind: Service
metadata:
  namespace: beta
  labels:
    app: beta
  name: beta
spec:
  ports:
  
    - protocol: TCP
      port: 9800
      targetPort: 9800
   
   
  selector:
    app: beta
  type: ClusterIP
